name: 'Build and Test QUICK MPI Version'

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-and-test-mpi-legacy-configure-make:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        compiler-version: [12, 13, 14]
    steps:
      - uses: actions/checkout@v4
      - name: 'Install Dependencies for MPI Version'
        run: |
          sudo apt-get update
          sudo apt-get -y install gcc-${{ matrix.compiler-version }} g++-${{ matrix.compiler-version }} gfortran-${{ matrix.compiler-version }} openmpi-bin openmpi-common libopenmpi-dev
      - name: 'Log Softare Environment Configuration'
        run: |
          echo "Ubuntu version:"
          cat /etc/os-release
          echo
          echo "Kernel version:"
          uname -a
          echo
          echo "Glibc version:"
          ldd --version
          echo
          echo "GCC (gfortran) version:"
          gfortran-${{ matrix.compiler-version }} --version
          echo
          echo "MPI version:"
          mpirun --version
      - name: 'Setup Environment Variables for Running Tests'
        run: |
          echo "QUICK_HOME=$PWD/install" >> "$GITHUB_ENV"
          echo "DO_PARALLEL=mpirun -np 2" >> "$GITHUB_ENV"
          echo "CC=gcc-${{ matrix.compiler-version }}" >> "$GITHUB_ENV"
          echo "CXX=g++-${{ matrix.compiler-version }}" >> "$GITHUB_ENV"
          echo "FC=gfortran-${{ matrix.compiler-version }}" >> "$GITHUB_ENV"
          echo "OMPI_CC=gcc-${{ matrix.compiler-version }}" >> "$GITHUB_ENV"
          echo "OMPI_CXX=g++-${{ matrix.compiler-version }}" >> "$GITHUB_ENV"
          echo "OMPI_FC=gfortran-${{ matrix.compiler-version }}" >> "$GITHUB_ENV"
      - name: 'Configure MPI Version'
        run: ./configure --mpi --enablef --prefix $PWD/install gnu
      - name: 'Build and Install MPI Version Using 2 Jobs'
        run: make -j2 all install
      - name: 'Run Tests for MPI Version (Make) Using 2 MPI Processes'
        run: make fulltest
      - name: 'Upload Test Artifacts for MPI Version'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mpi-legacy-configure-make-tests-gcc-${{ matrix.compiler-version }}
          path: /home/runner/work/QUICK/QUICK/install/test/runs/mpi
          retention-days: 3
          compression-level: 6
      - name: 'Download Test Artifacts for MPI Version'
        uses: actions/download-artifact@v4
        with:
          name: mpi-legacy-configure-make-tests-gcc-${{ matrix.compiler-version }}
      - name: 'Display Artifacts'
        run: ls -R
  build-and-test-mpi-cmake:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        compiler-version: [12, 13, 14]
    steps:
      - uses: actions/checkout@v4
      - name: 'Install Dependencies for MPI Version (CMake)'
        run: |
          sudo apt-get update
          sudo apt-get -y install gcc-${{ matrix.compiler-version }} g++-${{ matrix.compiler-version }} gfortran-${{ matrix.compiler-version }} cmake openmpi-bin openmpi-common libopenmpi-dev
      - name: 'Log Softare Environment Configuration (CMake)'
        run: |
          echo "Ubuntu version:"
          cat /etc/os-release
          echo
          echo "Kernel version:"
          uname -a
          echo
          echo "Glibc version:"
          ldd --version
          echo
          echo "GCC (gfortran) version:"
          gfortran-${{ matrix.compiler-version }} --version
          echo
          echo "MPI version:"
          mpirun --version
          echo
          echo "CMake version:"
          cmake --version
      - name: 'Setup Environment Variables for Running Tests'
        run: |
          echo "QUICK_HOME=$PWD/install" >> "$GITHUB_ENV"
          echo "DO_PARALLEL=mpirun -np 2" >> "$GITHUB_ENV"
          echo "CC=gcc-${{ matrix.compiler-version }}" >> "$GITHUB_ENV"
          echo "CXX=g++-${{ matrix.compiler-version }}" >> "$GITHUB_ENV"
          echo "FC=gfortran-${{ matrix.compiler-version }}" >> "$GITHUB_ENV"
          echo "OMPI_CC=gcc-${{ matrix.compiler-version }}" >> "$GITHUB_ENV"
          echo "OMPI_CXX=g++-${{ matrix.compiler-version }}" >> "$GITHUB_ENV"
          echo "OMPI_FC=gfortran-${{ matrix.compiler-version }}" >> "$GITHUB_ENV"
      - name: 'Configure MPI Version (CMake)'
        run: |
          mkdir build
          cd build
          cmake .. -DCOMPILER=MANUAL -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_Fortran_COMPILER=$FC -DMPI=TRUE -DENABLEF=TRUE -DCMAKE_INSTALL_PREFIX=$PWD/../install
      - name: 'Build and Install MPI Version (CMake) Using 2 Jobs'
        run: |
          cd build
          cmake --build . --parallel 2
          cmake --install .
      - name: 'Run Tests for MPI Version Using 2 MPI Processes'
        run: |
          cd install
          ./runtest --mpi --full
      - name: 'Upload Test Artifacts for MPI Version (CMake)'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mpi-cmake-tests-gcc-${{ matrix.compiler-version }}
          path: /home/runner/work/QUICK/QUICK/install/test/runs/mpi
          retention-days: 3
          compression-level: 6
      - name: 'Download Test Artifacts for MPI Version (CMake)'
        uses: actions/download-artifact@v4
        with:
          name: mpi-cmake-tests-gcc-${{ matrix.compiler-version }}
      - name: 'Display Artifacts'
        run: ls -R
